_maps/map_files/vaultcity/vaultcity.dmm
=> creative title

_maps/map_files/Pahrump/Pahrump-Surface-2.dmm, _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Adds in the pitrat base.
It's necessary.
:cl:
add: adds the pitrat base in place of the den's base
/:cl:
=> Pitrat base

_maps/map_files/Pahrump/Pahrump-Above-3.dmm, _maps/map_files/Pahrump/Pahrump-Surface-2.dmm, _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Includes some fixes to the base.
null
:cl:
/:cl:
=> Pit Rat Base update

code/modules/clothing/suits/f13factionarmor.dm
buffs NCR armor slightly
Slightly buffs NCR armor
:cl:
/:cl:
=> NCR armor buff

code/datums/components/crafting/recipes/recipes_medicine.dm, code/game/objects/items/storage/survivalkit.dm, code/modules/jobs/job_types/Kebab.dm, code/modules/jobs/job_types/legion.dm, code/modules/jobs/job_types/ncr.dm, code/modules/jobs/job_types/wasteland.dm, code/modules/reagents/chemistry/recipes/medicine.dm, fortune13.dme
=> med update

code/game/objects/items/storage/boxes.dm, code/modules/jobs/job_types/wasteland.dm
Replaces the loadout system that raiders had with gunboxes.
This removes the loadout meta.
:cl:
/:cl:
=> Raider update

config/admins.txt, config/config.txt, config/motd.txt, interface/skin.dmf
Updates the menu screen a bit
We're a different server
:cl:
/:cl:
=> Menu update

config/admins.txt
=> updates admin list

_maps/map_files/Pahrump/Pahrump-Above-3.dmm, _maps/map_files/Pahrump/Pahrump-Surface-2.dmm, _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Makes some minor quality of life changes to Kebab
:cl:
/:cl:
=> Kebab Map Update

_maps/map_files/Pahrump/Pahrump-Above-3.dmm, _maps/map_files/Pahrump/Pahrump-Surface-2.dmm, code/game/objects/items/manuals.dm
Lowers the prices listed on the recommended prices sheet and changes the author of the Purple Book.
=> Church Update

code/datums/datacore.dm, code/modules/clothing/head/helmet.dm, code/modules/jobs/job_types/church.dm, config/config.txt
fixes manifest
fixes stimpaks (idk why that worked)
changes roundstart station name to nukapop
fixes riot helmet not covering hair
=> manifest and stimpaks

code/controllers/subsystem/shuttle.dm, code/game/objects/items/binoculars.dm, code/modules/jobs/job_types/pitrats.dm, code/modules/research/designs/autolathe_designs.dm
=> fixes regular pitrat, makes shuttle timer 10 minutes and adds binocs as an autolathe recipe

code/modules/clothing/head/f13factionhead.dm, modular_citadel/code/modules/client/loadout/head.dm
See above.
Because it is.
:cl:
/:cl:
=> Removes the "+generic" thing from hats that doesn't work + fixes a loadout thing

code/modules/jobs/job_types/ncr.dm
=> SSGT was spawning with LT ID

_maps/map_files/Pahrump/Pahrump-Above-3.dmm, _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Remaps the radio station so the studio is on the bottom floor and the living area is on the upper floor.
Also fixes the display cases in the Merchant's house which were tampered with for some reason.
Because it is.
:cl:
/:cl:
=> Radio Station Remap

code/modules/fallout/obj/trash_stack.dm
Removes guns and caps from the trash piles.
The trash piles existed as free money machines basically
:cl:
/:cl:
=> Trash Update

_maps/map_files/Pahrump/Pahrump-Surface-2.dmm
See above.
Removes NCRCF uniforms from the NCR base because their presence didn't make sense.
Because it is.
:cl:
/:cl:
=> Removes NCRCF uniforms from the NCR base.

code/modules/jobs/job_types/ncr.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm
=> slepnir nerf

code/game/world.dm
Changes the discord link on the hub
=> config (discord link)

config/admins.txt
=> admin changes

code/modules/jobs/job_types/church.dm
=> neophyte buff

code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
=> makes gressil only able to smash through normal walls

code/modules/fallout/obj/manual/ncr/ncr_job_guide.dm
=> Updates the NCR uniform regs slightly

_maps/map_files/Pahrump/Pahrump-Surface-2.dmm
De-nests the entire plaza, removes some ugliness, removes the stupid ass "museum armory" with a historic weapon's display. Now featuring a suit of plastic combat armor to tease people with.
I will be doing similar PRs for almost every dungeon in the map until they aren't all so sucky.
=> Remaps the museum dungeon and surrounding plaza.

_maps/map_files/Pahrump/Pahrump-Surface-2.dmm
(I learned what pixel shifting is)
One clothing store is now focused on normal clothing, and the other is a costume store. They aren't just serving the exact same purpose anymore.
And, no, I do not feel like posting screenshots here. I have already done so in the discord.
=> Changes the two clothing stores, tweaks a few other things.

_maps/map_files/Pahrump/Pahrump-Surface-2.dmm
=> gutlunch feed storage

_maps/map_files/Pahrump/Pahrump-Underground-1.dmm
deletes the NCR bunker (it's not supposed to exist and fucks with spawns)
=> Deletes NCR bunker
